### ISSUE TITLE
Loading window

### ISSUE THREAD

**Issue by TheOnlyRealTGS** [WorldCretornica/LegacyConverter#3]
So currently I'm not sure if it's working, or nothing happened.
All I saw was a popup window informing that another popup would appear when it's done.
I clicked OK, and it now shows the start window.
It would be useful with a window indicating that it's converting.

**Comment by TheOnlyRealTGS** [comment]
I've waited a few hours and no window appeared. Does it work or?

**Comment by MarkusAV** [comment]
After its done converting it will appear another popup window. How large is your plots.db file?

**Comment by MattBDev** [comment]
Use commandline output or read the log file. this doesn't help me fix anything.

**Comment by TheOnlyRealTGS** [comment]
It's around 5 mb. What is the command to run it?
I've tired _java -jar LegacyConverter_

**Comment by MattBDev** [comment]
the syntax is in the readme file. It has the syntax you would use if you are using MySQL or SQLite

**Comment by TheOnlyRealTGS** [comment]
Ah now I get it. Version 0.17.1 contains the wrong syntax for the legacy converter.
